// Generated by CoffeeScript 1.10.0
(function() {
  this.App = (function() {
    function App() {}

    App.getUserLocation = function() {
      if (navigator.geolocation) {
        Helpers.events.fire('native-api-sent');
        return navigator.geolocation.getCurrentPosition(function(pos) {
          Helpers.events.fire('native-api-completed');
          return Helpers.events.fire('app-location-found', pos.coords);
        }, function(error) {
          return Helpers.events.fire('native-api-error', (function() {
            switch (error.code) {
              case error.PERMISSION_DENIED:
                return 'Denied request to geolocate user';
              case error.POSITION_UNAVAILABLE:
                return 'Could not detect user location';
              case error.TIMEOUT:
                return 'Attempt to find user timed out';
              case error.UNKNOWN_ERROR:
                return 'Unknown error in geolocation';
            }
          })());
        });
      } else {
        return ui.displayAlert('Your browser does not support geolocation', true);
      }
    };

    return App;

  })();

}).call(this);
