// Generated by CoffeeScript 1.10.0
(function() {
  this.App = (function() {
    function App() {}

    App.getUserLocation = function(callback) {
      if (navigator.geolocation) {
        Helpers.events.fire('mbta-api-sent');
        return navigator.geolocation.getCurrentPosition(function(pos) {
          Helpers.events.fire('mbta-api-completed');
          return callback(pos.coords);
        }, function(error) {
          Helpers.events.fire('mbta-api-error');
          switch (error.code) {
            case error.PERMISSION_DENIED:
              return ui.displayAlert('Denied request to geolocate user', true);
            case error.POSITION_UNAVAILABLE:
              return ui.displayAlert('Could not detect user location', true);
            case error.TIMEOUT:
              return ui.displayAlert('Attempt to find user timed out', true);
            case error.UNKNOWN_ERROR:
              return ui.displayAlert('Unknown error in geolocation', true);
          }
        });
      } else {
        return ui.displayAlert('Your browser does not support geolocation', true);
      }
    };

    return App;

  })();

}).call(this);
