// Generated by CoffeeScript 1.4.0
(function() {

  this.Mapper = (function() {

    function Mapper() {}

    Mapper.map = null;

    Mapper.defaultStops = [];

    Mapper.defaultRouteIds = ["741", "742", "746", "749", "751", "Green-B", "Green-C", "Green-D", "Green-E", "Red", "Blue", "Orange"];

    Mapper.defaultStopIds = [];

    Mapper.center = {
      lat: 42.358,
      lng: -71.064
    };

    Mapper.selected = null;

    Mapper.pendingSelectionEvent = null;

    Mapper.zoom = 14;

    Mapper.featureManager = {
      _features: {},
      addFeature: function(key, feature) {
        Mapper.featureManager.destroyFeature(key);
        Mapper.featureManager._features[key] = feature;
        return Mapper.featureManager.renderFeature(key);
      },
      getFeature: function(key) {
        return Mapper.featureManager._features[key];
      },
      destroyFeature: function(key) {
        var feature, subfeature, _i, _len, _results;
        if (!Mapper.featureManager._features[key]) {
          return;
        }
        feature = Mapper.featureManager._features[key];
        if (feature.constructor === Array) {
          _results = [];
          for (_i = 0, _len = feature.length; _i < _len; _i++) {
            subfeature = feature[_i];
            _results.push(subfeature.destroy());
          }
          return _results;
        } else {
          return feature.destroy();
        }
      },
      renderFeature: function(key) {
        var feature, subfeature, _i, _len, _results;
        if (!Mapper.featureManager._features[key]) {
          return;
        }
        feature = Mapper.featureManager._features[key];
        if (feature.constructor === Array) {
          _results = [];
          for (_i = 0, _len = feature.length; _i < _len; _i++) {
            subfeature = feature[_i];
            _results.push(subfeature.render());
          }
          return _results;
        } else {
          return feature.render();
        }
      }
    };

    Mapper.initialize = function() {
      Mapper.map = new google.maps.Map(document.getElementById('viewport'), {
        center: Mapper.center,
        zoom: Mapper.zoom,
        styles: jsonData.google_style,
        backgroundColor: '#2a2a2a',
        disableDefaultUI: true
      });
      Mapper.map.addListener('click', function(clickData) {
        return Mapper.displayLocation({
          latitude: clickData.latLng.lat(),
          longitude: clickData.latLng.lng()
        });
      });
      Mapper.featureManager.addFeature('defaultRoutes', Mapper.defaultRouteIds.map(function(routeId) {
        var route;
        route = jsonData.routes[routeId];
        return new Route(route.id, route.name, route.mode);
      }));
      Mapper.defaultStopIds = jsonData.default_stops;
      Mapper.featureManager.addFeature('defaultStops', Mapper.defaultStopIds.map(function(stopId) {
        var stop;
        stop = jsonData.stops[stopId];
        return new Stop(stop.id, stop.name, stop.lat, stop.lon, "Bus");
      }));
      Helpers.events.bind('modal-closed', Mapper.removeSelected);
      Helpers.events.bind('app-location-found', Mapper.displayLocation);
      Helpers.events.bind('stop-selected', Mapper.markStopSelected);
      Helpers.events.bind('stop-fetchdata-success', function() {
        return Mapper.markSelectedStopState('success');
      });
      return Helpers.events.bind('stop-fetchdata-error', function() {
        Mapper.markSelectedStopState('error');
        return Mapper.pendingSelectionEvent = setTimeout(Mapper.removeSelected, 2000);
      });
    };

    Mapper.drawRoutesForStops = function(stops) {
      return async.map(stops, function(stop, subCallback) {
        return Mbta.getRoutesByStop(stop, true, {
          success: function(routes) {
            return subCallback(null, routes);
          },
          error: console.error
        });
      }, function(error, allRoutes) {
        var nonDefaultUniqueRoutes, uniqueRoutes;
        if (error) {
          return console.error(error);
        } else {
          uniqueRoutes = _.uniq(_.flatten(allRoutes), false, function(route) {
            return route.id;
          });
          nonDefaultUniqueRoutes = _.reject(uniqueRoutes, function(route) {
            return Mapper.defaultRouteIds.indexOf(route.id) !== -1;
          });
          return Mapper.featureManager.addFeature('traced-route', nonDefaultUniqueRoutes);
        }
      });
    };

    Mapper.displayLocation = function(coords) {
      Mapper.featureManager.addFeature('user-location', new LocationMarker(coords.latitude, coords.longitude));
      Mapper.zoomToLocation(coords);
      return Mbta.getNearbyStops(coords, {
        success: function(stops) {
          Mapper.drawRoutesForStops(stops);
          return Mapper.featureManager.addFeature('local-stops', stops);
        },
        error: console.error
      });
    };

    Mapper.markSelectedStopState = function(state) {
      var currentIcon;
      currentIcon = Mapper.selected.getIcon();
      currentIcon.url = (function() {
        switch (state) {
          case 'error':
            return Helpers.iconUrls.selectedError;
          case 'success':
            return Helpers.iconUrls.selectedSuccess;
        }
      })();
      return Mapper.selected.setIcon(currentIcon);
    };

    Mapper.markStopSelected = function(marker) {
      if (Mapper.selected != null) {
        Mapper.removeSelected();
      }
      return Mapper.selected = new google.maps.Marker({
        position: new google.maps.LatLng(marker.lat, marker.lng),
        map: Mapper.map,
        icon: {
          url: Helpers.iconUrls.selected,
          scaledSize: new google.maps.Size(33, 33),
          anchor: new google.maps.Point(16, 16)
        }
      });
    };

    Mapper.placeMarker = function(lat, lon, title, icon) {
      return new google.maps.Marker({
        position: new google.maps.LatLng(lat, lon),
        map: Mapper.map,
        title: title,
        icon: icon
      });
    };

    Mapper.placeVehicleMarker = function(marker) {
      return Mapper.placeMarker(marker.lat, marker.lng, marker.destination, marker.icon || Helpers.getLiveIcon(marker));
    };

    Mapper.placeStopMarker = function(marker) {
      var gMarker;
      gMarker = Mapper.placeMarker(marker.lat, marker.lng, marker.name, marker.icon || Helpers.getIcon(marker));
      google.maps.event.addListener(gMarker, 'click', function() {
        return Mapper.click.stopMarker(marker);
      });
      return gMarker;
    };

    Mapper.placeStopMarkers = function(markers, extractor) {
      if (extractor == null) {
        extractor = function(marker) {
          return marker;
        };
      }
      return $.each(markers, function(i, marker) {
        return Mapper.placeStopMarker(extractor(marker));
      });
    };

    Mapper.removeSelected = function() {
      if (Mapper.pendingSelectionEvent) {
        clearTimeout(Mapper.pendingSelectionEvent);
      }
      if (Mapper.selected) {
        Mapper.selected.setMap(null);
        return Mapper.selected = null;
      }
    };

    Mapper.zoomToLocation = function(location) {
      Mapper.map.setCenter(new google.maps.LatLng(location.latitude, location.longitude));
      return Mapper.map.setZoom(16);
    };

    return Mapper;

  })();

}).call(this);
